services:
  db:
    container_name: db
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT}:5432"
    env_file:
      - ./.env
    networks:
      - app-network

  app:
    depends_on:
      - db
    container_name: app
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
      args:
        DEV_SERVER_PORT: ${DEV_SERVER_PORT}
    volumes:
      - ./logs/:/app/logs/
    working_dir: /app
    environment:
      # We selectively expose env variables to the container to make sure that it can never launch in a development environment on Docker
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}?schema=public
      - DEV_SERVER_PORT=${DEV_SERVER_PORT}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ENDPOINT_API_KEY=${ENDPOINT_API_KEY}
    ports:
      - "${SERVER_PORT}:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge