name: Backend CI
on:
  push:
    branches:
      - "**" # all branches

env:
  CI: true

jobs:
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Lint
        run: |
          npm install
          npm run ci:lint
        working-directory: ./backend
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v4
        with:
          node-version: "22"
      - name: Install
        run: |
          npm install
          npm run ci:prettier
        working-directory: ./backend
